package com.portfolio.social_media_api.Model;

import lombok.*;
import jakarta.persistence.*;

@EqualsAndHashCode
@Entity
@Table(name="message")
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Message {

	// @GeneratedValue
	@Column (name="messageId")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer messageId;

	@Column (name="postedBy")
    private Integer postedBy;

    @Column (name="messageText")
    private String messageText;

	@Column (name="timePostedEpoch")
    private Long timePostedEpoch;


	//  When posting a new message, the id can be generated by the database. In that case, a constructor without
    //  messageId is needed.
    public Message(Integer postedBy, String messageText, Long timePostedEpoch) {
        this.postedBy = postedBy;
        this.messageText = messageText;
        this.timePostedEpoch = timePostedEpoch;
    }

	// @Override
	// public boolean equals(Object obj) {
	// 	if (this == obj)
	// 		return true;
	// 	if (obj == null)
	// 		return false;
	// 	if (getClass() != obj.getClass())
	// 		return false;
	// 	Message other = (Message) obj;
	// 	if (messageId == null) {
	// 		if (other.messageId != null)
	// 			return false;
	// 	} else if (!messageId.equals(other.messageId))
	// 		return false;
	// 	if (messageText == null) {
	// 		if (other.messageText != null)
	// 			return false;
	// 	} else if (!messageText.equals(other.messageText))
	// 		return false;
	// 	if (postedBy == null) {
	// 		if (other.postedBy != null)
	// 			return false;
	// 	} else if (!postedBy.equals(other.postedBy))
	// 		return false;
	// 	if (timePostedEpoch == null) {
	// 		if (other.timePostedEpoch != null)
	// 			return false;
	// 	} else if (!timePostedEpoch.equals(other.timePostedEpoch))
	// 		return false;
	// 	return true;
	// }

    @Override
    public String toString() {
        return "Message{" +
                "messageId=" + messageId +
                ", postedBy=" + postedBy +
                ", messageText='" + messageText + '\'' +
                ", timePostedEpoch=" + timePostedEpoch +
                '}';
    }
}